image:
  file: .gitpod.Dockerfile

ports:
  # app server
  - port: 8080
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: |
      mv cmd/config.yaml.example cmd/config.yaml
      mysql -e "CREATE DATABASE my_apijson;"
      mysql -p my_apijson < cmd/test/test.sql
      mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'yourpassword';"

    command: |
      go mod tidy
      go run cmd/main.go

vscode:
  extensions:
    - golang.Go
    - humao.rest-client