name: tests
on:
  push:
    branches: [ "main" ,"dev"]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: cd test && go test -short
